<a href="https://colab.research.google.com/github/Augustine0077/Numpy-pandas/blob/main/datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mylist=[1,2,3]
type(mylist)

list

In [ ]:
mylist

[1, 2, 3]

In [ ]:
myarry=np.array( mylist)


In [ ]:
myarry

array([1, 2, 3])

In [ ]:
my_metrix=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_metrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_metrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.randn(2,3)

array([[ 1.78862847,  0.43650985,  0.09649747],
       [-1.8634927 , -0.2773882 , -0.35475898]])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.random.rand(100,100)

array([[0.0514672 , 0.44080984, 0.02987621, ..., 0.54359433, 0.08979087,
        0.48887324],
       [0.92793635, 0.7876182 , 0.48509423, ..., 0.43635708, 0.49778283,
        0.58331192],
       [0.62051268, 0.3728115 , 0.61873658, ..., 0.54317945, 0.55736739,
        0.86855463],
       ...,
       [0.8857434 , 0.85629273, 0.03479746, ..., 0.30736845, 0.00862262,
        0.96744412],
       [0.33676109, 0.06146013, 0.32221297, ..., 0.94018084, 0.58107328,
        0.78771174],
       [0.45776725, 0.07997483, 0.4476462 , ..., 0.22265047, 0.36936852,
        0.49889354]])

In [ ]:
np.random.randint(1,100,(2,3))

array([[48, 73, 29],
       [49, 21, 68]])

In [ ]:
import numpy as np

In [ ]:
np.random.seed(3)
np.random.rand(0,10)

array([], shape=(0, 10), dtype=float64)

In [ ]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

24

In [ ]:
arr.min()

0

here can specify the index

In [ ]:
arr.argmax()

24

In [ ]:
arr.argmin()

0

the datatype can call

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5).shape


(5, 5)

In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[:1]

array([[1, 2, 3]])

In [ ]:
a=np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a>=10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
bool_arr=a>=40
a[bool_arr]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# ***Pandas***

In [7]:
import numpy as np
import pandas as pd
#help(pd.Series)

In [ ]:
myindex=['USA','CANADA','MEXICO']
mydata=[1776,1867,1821]
myser=pd.Series(mydata,myindex)
myser

USA       1776
CANADA    1867
MEXICO    1821
dtype: int64

In [ ]:
myser['USA']

1776

In [ ]:
ages={'Sam':5,'Frank':10,'Spike':7}
pd.Series(ages)

Sam       5
Frank    10
Spike     7
dtype: int64

In [1]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}

q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [8]:
sails_q1=pd.Series(q1)


In [9]:
sails_q2=pd.Series(q2)

In [10]:
sails_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [12]:
sails_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [16]:
sails_q1['Japan']

80

In [18]:
sails_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [21]:
np.array([1,2])*2
sails_q2 *2

Brazil     200
China     1000
India      420
USA        520
dtype: int64

In [24]:
sails_q1+sails_q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [27]:
sails_q1.add(sails_q2,fill_value=0)


Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [28]:
pd.Series

pandas.core.series.Series

In [29]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}

q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [31]:
sails_q1=pd.Series(q1)
sails_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [32]:
sails_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [33]:
sails_q1['Japan']

80

In [36]:
import numpy as np
import pandas as pd

In [43]:
#np.random.seed(101)
my_data= np.random.randint(0,101,(4,3))
my_data

array([[40, 60, 92],
       [64,  5, 12],
       [93, 40, 49],
       [83,  8, 29]])

In [47]:
my_index=['CA','NY','AZ','TX']
my_columns=['Jan','Feb','Mar']
df=pd.DataFrame(my_data,my_index,my_columns)
df

Jan  Feb  Mar
CA   40   60   92
NY   64    5   12
AZ   93   40   49
TX   83    8   29

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes
